apiVersion: v1
kind: Pod
metadata:
  name: ma-pod
  namespace: default
  labels:
    app: pod
spec:
  containers:
  - name: myapp
    image: busybox:1.28
    command: ['sh', '-c', "sleep 3660 && exit 0"]
    volumeMounts:
      - name: configmap-volume
        mountPath: /configmap-volume
      - name: configmap-volume
        mountPath: /configmap-volume2/username
        subPath: username
  volumes:
    - name: configmap-volume
      configMap:
        name: ma-configmap
        items:
        - key: users.list
          path: userslist
        - key: username
          path: username
  restartPolicy: Never