apiVersion: v1
kind: Pod
metadata:
  name: ma-pod
  namespace: default
  labels:
    app: pod
spec:
  containers:
  - name: myapp-container-1
    image: busybox:1.28
    command: ['sh', '-c', "echo The app is running!${DEMO_GREETING} from ${POD_NAME} && sleep 10"]
    env: 
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
