apiVersion: v1
kind: Pod
metadata:
  name: ma-pod
  namespace: default
  labels:
    app: pod
spec:
  containers:
  - name: myapp-container-1
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running in the 1st container! && sleep 30']
  - name: myapp-container-2
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running in the 2nd container! && sleep 30']